# ===== Left Hand open pos =====
# Joint angles
LEFT_THUMB_OPEN_CMC = 159.5
LEFT_THUMB_OPEN_MCP = 176.8
LEFT_THUMB_OPEN_IP  = 176.5

LEFT_INDEX_OPEN_MCP = 172.7
LEFT_INDEX_OPEN_PIP = 179.6
LEFT_INDEX_OPEN_DIP = 178.5

LEFT_MIDDLE_OPEN_MCP = 165.8
LEFT_MIDDLE_OPEN_PIP = 178.3
LEFT_MIDDLE_OPEN_DIP = 177.6

LEFT_RING_OPEN_MCP = 166.6
LEFT_RING_OPEN_PIP = 177.3
LEFT_RING_OPEN_DIP = 177.8

LEFT_PINKY_OPEN_MCP = 162.9
LEFT_PINKY_OPEN_PIP = 177.1
LEFT_PINKY_OPEN_DIP = 179.5

# Inter-finger angles
LEFT_THUMB_INDEX_OPEN  = 72
LEFT_INDEX_MIDDLE_OPEN = 14.6
LEFT_MIDDLE_RING_OPEN  = 13.7
LEFT_RING_PINKY_OPEN   = 15.4

# ===== Right Hand open pos =====
# Joint angles
RIGHT_THUMB_OPEN_CMC = 163.4
RIGHT_THUMB_OPEN_MCP = 177.0
RIGHT_THUMB_OPEN_IP  = 171.8

RIGHT_INDEX_OPEN_MCP = 174.2
RIGHT_INDEX_OPEN_PIP = 179.4
RIGHT_INDEX_OPEN_DIP = 177.3

RIGHT_MIDDLE_OPEN_MCP = 165.7
RIGHT_MIDDLE_OPEN_PIP = 175.0
RIGHT_MIDDLE_OPEN_DIP = 179.5

RIGHT_RING_OPEN_MCP = 162.4
RIGHT_RING_OPEN_PIP = 172.9
RIGHT_RING_OPEN_DIP = 176.0

RIGHT_PINKY_OPEN_MCP = 159.0
RIGHT_PINKY_OPEN_PIP = 173.9
RIGHT_PINKY_OPEN_DIP = 179.1

# Inter-finger angles
RIGHT_THUMB_INDEX_OPEN  = 39.0
RIGHT_INDEX_MIDDLE_OPEN = 15.3
RIGHT_MIDDLE_RING_OPEN  = 13.3
RIGHT_RING_PINKY_OPEN   = 16.4

# ===== Left Hand close pos =====
# Joint angles
LEFT_THUMB_CLOSE_CMC = 157.6
LEFT_THUMB_CLOSE_MCP = 149.9
LEFT_THUMB_CLOSE_IP  = 113.4

LEFT_INDEX_CLOSE_MCP = 111.8
LEFT_INDEX_CLOSE_PIP = 77.8
LEFT_INDEX_CLOSE_DIP = 116.9

LEFT_MIDDLE_CLOSE_MCP = 104.2
LEFT_MIDDLE_CLOSE_PIP = 83.2
LEFT_MIDDLE_CLOSE_DIP = 136.0

LEFT_RING_CLOSE_MCP = 97.2
LEFT_RING_CLOSE_PIP = 84.0
LEFT_RING_CLOSE_DIP = 140.4

LEFT_PINKY_CLOSE_MCP = 100.0
LEFT_PINKY_CLOSE_PIP = 87.9
LEFT_PINKY_CLOSE_DIP = 134.6

# Inter-finger angles
LEFT_THUMB_INDEX_CLOSE  = 39.0
LEFT_INDEX_MIDDLE_CLOSE = 15.8
LEFT_MIDDLE_RING_CLOSE  = 14.6
LEFT_RING_PINKY_CLOSE   = 17.9

# ===== Right Hand close pos =====
# Joint angles
RIGHT_THUMB_CLOSE_CMC = 166.6
RIGHT_THUMB_CLOSE_MCP = 151.5
RIGHT_THUMB_CLOSE_IP  = 113.9

RIGHT_INDEX_CLOSE_MCP = 105.9
RIGHT_INDEX_CLOSE_PIP = 82.8
RIGHT_INDEX_CLOSE_DIP = 125.9

RIGHT_MIDDLE_CLOSE_MCP = 98.3
RIGHT_MIDDLE_CLOSE_PIP = 84.0
RIGHT_MIDDLE_CLOSE_DIP = 130.5

RIGHT_RING_CLOSE_MCP = 93.8
RIGHT_RING_CLOSE_PIP = 82.7
RIGHT_RING_CLOSE_DIP = 141.1

RIGHT_PINKY_CLOSE_MCP = 102.6
RIGHT_PINKY_CLOSE_PIP = 82.8
RIGHT_PINKY_CLOSE_DIP = 131.1

# Inter-finger angles
RIGHT_THUMB_INDEX_CLOSE  = 19.0
RIGHT_INDEX_MIDDLE_CLOSE = 16.3
RIGHT_MIDDLE_RING_CLOSE  = 14.9
RIGHT_RING_PINKY_CLOSE   = 17.7

# ===== Tip-to-tip distances (for pinch/OK gestures) =====
# Measured as Euclidean distance between finger tips (in meters, wrist-centered)
# d_open = tips far apart, d_close ≈ 0 (tips touching)
# These values need to be calibrated by running hand_graphics_plot_after_calibration.py
# and reading the "tip_dist" values in open-hand and OK-sign poses.
# Placeholder values below — update after calibration!
LEFT_THUMB_INDEX_TIP_DIST_OPEN  = 0.15   # open hand: tips far apart
LEFT_THUMB_INDEX_TIP_DIST_CLOSE = 0.01   # OK sign: tips touching

RIGHT_THUMB_INDEX_TIP_DIST_OPEN  = 0.15
RIGHT_THUMB_INDEX_TIP_DIST_CLOSE = 0.01
